# Pre-commit configuration for the groceries project
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # General hooks for file formatting and validation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first

  # Linting and code quality with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - click>=8.2.1
          - google-api-python-client>=2.177.0
          - google-auth>=2.40.3
          - google-auth-httplib2>=0.2.0
          - google-auth-oauthlib>=1.2.2
          - pydantic-ai[logfire]>=0.0.13
          - python-dotenv>=1.0.1
        args: [--config-file=pyproject.toml]

  # Security checks with bandit
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: [-c, pyproject.toml]
        additional_dependencies: ["bandit[toml]"]

# Configuration for pre-commit
default_language_version:
  python: python3.13

# Exclude files/directories from all hooks
exclude: |
  (?x)^(
    __pycache__/.*|
    .*\.pyc$|
    .*\.pyo$|
    .*\.egg-info/.*|
    .*/migrations/.*
  )$
